// web-frontend/src/routes/login/+page.svelte
<script>
	let info = {
		email: "",
		password: ""
	};

	let error = "";

	async function login() {
		let res = await fetch("/auth/login", {
			method: "POST",
			body: JSON.stringify(info)
		});
		if (!res.ok) {
			let json = await res.json();
			error = json.error;
		}
	}
</script>

<div class="main col col-md text-center">
	<h1>Login</h1>
	<div class="col spaced-top-2">
		<input type="email" placeholder="Email Address" bind:value={info.email} />
		<input type="password" placeholder="Password" bind:value={info.password} />
	</div>
	<p class="text-right">
		<a href="/register">Don't have an account?</a>
	</p>
	{#if error}
		<p>{error}</p>
	{/if}
	<button on:click={login}>Login</button>
</div>

// frontend/src/routes/Login.jsx
import { Alert, Button, Col, Container, Form, Row } from "solid-bootstrap";
import Header from "../components/Header";
import { createSignal } from "solid-js";
import { useNavigate } from "@solidjs/router";

export default function Home() {
  const navigate = useNavigate();

  let [showError, setShowError] = createSignal(false);
  let [form, setForm] = createSignal({
    email: "",
    passCode: "",
  });

  let updateForm = (e) => {
    setForm({ ...form(), [e.target.name]: e.target.value });
  };

  let submit = async (e) => {
    e.preventDefault();

    try {
      let res = await fetch("https://localhost:8000/auth/login", {
        method: "POST",
        body: JSON.stringify(form()),
      });

      if (res.ok) {
        navigate("/");
      } else {
        setShowError(true);
      }
    } catch (e) {
      setShowError(true);
    }
  };

  return (
    <>
      <Header />
      <Container>
        <Row>
          <Col md={4} class="mx-auto">
            <div class="text-center">
              <h1 class="mt-4 mx-auto">Login</h1>
            </div>
            <Show when={showError()}>
              <Alert variant="danger">Unable to authenticate</Alert>
            </Show>
            <Form onSubmit={submit}>
              <Form.Group class="mb-3">
                <Form.Label>Email Address</Form.Label>
                <Form.Control
                  name="email"
                  type="email"
                  placeholder="Email Address"
                  required
                  value={form().email}
                  onInput={updateForm}
                />
              </Form.Group>
              <Form.Group class="mb-3">
                <Form.Label>Pass Code</Form.Label>
                <Form.Control
                  name="passCode"
                  type="text"
                  placeholder="Pass Code"
                  maxLength={6}
                  required
                  value={form().passCode}
                  onInput={updateForm}
                />
              </Form.Group>
              <a class="mt-1 mb-1" href="/register">
                <p>Don't have an account?</p>
              </a>
              <div class="w-full text-right">
                <Button variant="primary" type="submit" value="submit">
                  Login
                </Button>
              </div>
            </Form>
          </Col>
        </Row>
      </Container>
    </>
  );
}
